# **Project 2 - Sales Analysis - ETL**

## Objectives

- Extract data from provided CSV files
- Clean it 
- Apply feature engineering if necessary 
- Remove any unnecessary columns
- Save to a new CSV file


## Inputs

CSV files provided:

stores data-set.csv
sales data-set.csv
features data set.csv

Renamed files to a uniform naming convention:

Sales_Features_DataSet.csv
Sales_DataSet.csv
Sales_Stores_DataSet.csv

Note: original files are stored in Data/OriginalFiles


## Outputs

CSV file created from ETL etc stored in Data/CleanedDataSets:

Sales_Features_DataSet_Cleaned.csv



## Additional Comments

Developed an experimental ETL library which is in this project (modETL_library.py) 
Has lots of cool features so will be interesting to see how it works "in the field"

Used AI tool used to help with the ETL process:
- GitHub 
- Copilot 

See Documents/What_AI_Used_For.md for more details.

## Initalise Working Environment

In [1]:
#import libraries
import os
import numpy as np
import pandas as pd

#below solution provided by chatGPT 
import sys
from pathlib import Path

project_root = Path.cwd().parent

if str(project_root / "assets" / "python_files") not in sys.path:
    sys.path.insert(0, str(project_root / "assets" / "python_files"))
    
import modGlobal
import modETL_Library as modETL
#end solution provided by chatGPT

# Section 1 - Initalisation

## Intitialise All Variables To Be Used In Global Stack

In [ ]:
#DataFrame vars for ETL
dfSales_Features_DataSet = None
dfSales_Features_DataSet_Work = None
dfCleaned = None

#missing values check vars
intLessThanZero = 0

#stores current directory
strCurrentDir = ""

#other vars
dictDataFrames = dict()
lstColumns = list()

## Set Current Directory To Base Project Directory

In [3]:
#get project directory - default is jupyter notebook sub folder as that is where this file is located!
#so move back one to the project root path
# Source - https://stackoverflow.com/a/17726833
# Posted by chimpsarehungry
# Retrieved 2026-07-05, License - CC BY-SA 3.0

#get current folder
strCurrentDir = os.getcwd()

#is the last part of the path the project directory?
if not strCurrentDir.endswith(modGlobal.CNST_STR_PROJECT_DIR):
   #get current working directory and move back one to the project root path
   strCurrentDir =  os.path.normpath(os.getcwd() + os.sep + os.pardir)
   os.chdir(os.path.dirname(strCurrentDir))
   #change directory
   os.chdir(strCurrentDir)

#confirm current directory is project directory
print(f"Current Directory: \n {os.getcwd()}")

Current Directory:
 /Users/rogerwilliams/Projects/Python/CourseProjects/Project2-SalesAnalysis

# Section 1 - Extraction

- Read csv file sales data-set.csv as other two do not require ETL (boo!)
- Move into working files directory
- Read csv file into a pandas dataframe
- Get schema info -> column and row numbers
- Get first 5 records
- Get list of column datatypes
- Get detailed schema infomation

## Read csv File Into Variable For Processing

In [4]:
#read csv file into DataFrame
dfSales_Features_DataSet = modETL.funcReadFileReturnDataFrame("Features_DataSet.csv")
#save as working csv file
modETL.funcSaveDataFrameToWorkingFile(dfSales_Features_DataSet)

#read file from working files folder
#ETL library returns a dictionary of all files in the folder with the attribute name
#set to the actual csv filename
dictDataFrames = modETL.funcReadWorkingFilesReturnDictionary()
dfSales_Features_DataSet = dictDataFrames["Features_DataSet_Working.csv"]

Folder Structure Created Successfully!
Read Features_DataSet.csv Into DataFrame

Saved: Features_DataSet To Working Folder
3 csv Files Read Into DataFrames

DataFrames Created:
Features_DataSet_Working.csv
Stores_DataSet_Working.csv
Sales_DataSet_Working.csv

## Get Schema Info - Sales_Features_DataSet

In [5]:
modETL.funcGetStructure(dfSales_Features_DataSet)
dfSales_Features_DataSet.head()

DataFrame Structure:
===================
<class 'pandas.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8190 non-null   int64
 1   Store         8190 non-null   int64
 2   Date          8190 non-null   str
 3   Temperature   8190 non-null   float64
 4   Fuel_Price    8190 non-null   float64
 5   MarkDown1     4032 non-null   float64
 6   MarkDown2     2921 non-null   float64
 7   MarkDown3     3613 non-null   float64
 8   MarkDown4     3464 non-null   float64
 9   MarkDown5     4050 non-null   float64
 10  CPI           7605 non-null   float64
 11  Unemployment  7605 non-null   float64
 12  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(2), str(1)
memory usage: 855.9 KB
None


Summary of DataFrame Structure:
===============================
Numeric Columns:

        Unnamed: 0        Store  Temperature   Fuel_Price      MarkDown1  \
count  8190.000000  8190.000000  8190.000000  8190.000000    4032.000000
mean   4094.500000    23.000000    59.356198     3.405992    7032.371786
std    2364.393685    12.987966    18.678607     0.431337    9262.747448
min       0.000000     1.000000    -7.290000     2.472000   -2781.450000
25%    2047.250000    12.000000    45.902500     3.041000    1577.532500
50%    4094.500000    23.000000    60.710000     3.513000    4743.580000
75%    6141.750000    34.000000    73.880000     3.743000    8923.310000
max    8189.000000    45.000000   101.950000     4.468000  103184.980000

           MarkDown2      MarkDown3     MarkDown4      MarkDown5          CPI  \
count    2921.000000    3613.000000   3464.000000    4050.000000  7605.000000
mean     3384.176594    1760.100180   3292.935886    4132.216422   172.460809
std      8793.583016   11276.462208   6792.329861   13086.690278    39.738346
min      -265.760000    -179.260000      0.220000    -185.170000   126.064000
25%        68.880000       6.600000    304.687500    1440.827500   132.364839
50%       364.570000      36.260000   1176.425000    2727.135000   182.764003
75%      2153.350000     163.150000   3310.007500    4832.555000   213.932412
max    104519.540000  149483.310000  67474.850000  771448.100000   228.976456

       Unemployment
count   7605.000000
mean       7.826821
std        1.877259
min        3.684000
25%        6.634000
50%        7.806000
75%        8.567000
max       14.313000


String Columns:

              Date
count         8190
unique         182
top     05/02/2010
freq            45


No DateTime   Columns Found!

,Unnamed: 0,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

## Observations - Sales_Features_DataSet
8190 rows
13 columns

Columns:

Unnamed, Store, Date, Temperature, Fuel_Price, MarkDown1, MarkDown2, MarkDown3, MarkDown4, MarkDown5, 
CPI, Unemployment, IsHoliday

Assuming Unnamed is an index column and can be dropped if necessary

We can also see the data types:

Unnamed : int64
Store : int64
Type : str
Size : int64

In the Summary of Dataframe Structure for numerical values we see this:

DataFrame Structure:
===================
<class 'pandas.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Unnamed: 0    8190 non-null   int64  
 1   Store         8190 non-null   int64  
 2   Date          8190 non-null   str    
 3   Temperature   8190 non-null   float64
 4   Fuel_Price    8190 non-null   float64
 5   MarkDown1     4032 non-null   float64
 6   MarkDown2     2921 non-null   float64
 7   MarkDown3     3613 non-null   float64
 8   MarkDown4     3464 non-null   float64
 9   MarkDown5     4050 non-null   float64
 10  CPI           7605 non-null   float64
 11  Unemployment  7605 non-null   float64
 12  IsHoliday     8190 non-null   bool   
dtypes: bool(1), float64(9), int64(2), str(1)
memory usage: 775.9 KB
None

Summary of DataFrame Structure:
===============================
Numeric Columns:

        Unnamed: 0        Store  Temperature   Fuel_Price      MarkDown1  \
count  8190.000000  8190.000000  8190.000000  8190.000000    4032.000000   
mean   4094.500000    23.000000    59.356198     3.405992    7032.371786   
std    2364.393685    12.987966    18.678607     0.431337    9262.747448   
min       0.000000     1.000000    -7.290000     2.472000   -2781.450000   
25%    2047.250000    12.000000    45.902500     3.041000    1577.532500   
50%    4094.500000    23.000000    60.710000     3.513000    4743.580000   
75%    6141.750000    34.000000    73.880000     3.743000    8923.310000   
max    8189.000000    45.000000   101.950000     4.468000  103184.980000   

           MarkDown2      MarkDown3     MarkDown4      MarkDown5          CPI  \
count    2921.000000    3613.000000   3464.000000    4050.000000  7605.000000   
mean     3384.176594    1760.100180   3292.935886    4132.216422   172.460809   
std      8793.583016   11276.462208   6792.329861   13086.690278    39.738346   
min      -265.760000    -179.260000      0.220000    -185.170000   126.064000   
25%        68.880000       6.600000    304.687500    1440.827500   132.364839   
50%       364.570000      36.260000   1176.425000    2727.135000   182.764003   
75%      2153.350000     163.150000   3310.007500    4832.555000   213.932412   
max    104519.540000  149483.310000  67474.850000  771448.100000   228.976456   

       Unemployment  
count   7605.000000  
mean       7.826821  
std        1.877259  
min        3.684000  
25%        6.634000  
50%        7.806000  
75%        8.567000  
max       14.313000  

**What Does This Mean?**

- Count is how many values are in the columns
- Mean is the average value of the column
- Std is the standard deviation of the column 
  Standard deviation is how far from the average (mean) the values are. The closer to 0 the
  more consistent the values are i.e. not much deviation from the mean. The deviation range 
  can be referred to as the Sigma. The measurement is based on the Alpha this is a percentage
  of the mean used to determine variance. ypically this is set to 5%
- Min is the minimum value of the column
- 25% is the value at the 25th percentile of the column
- 50% is the value between the 25th and 75th percentiles of the column
- 75% is the value at the 75th percentile of the column

The middle 50% is also called the Interquartile Range (IQR) and its width can be set by changing the
alpha value which is normally 5%

**What?**

Percentile is a technical term for a 25% segment of the data. 
50% is the mean, 25% is below that and 75% is 25%above that, this crude picture illustrates this:

 1st Percentile      2nd Percentile        3rd Percentile
0      -      25%  25%      -     75%   75%      -     100%  

Note: 2nd percentile can also be called Central Tendency

- Max is the maximum value of the column

String Columns:

              Date
count         8190 - number of records  
unique         182 - number of unique values
top     05/02/2010 - most frequent value 
freq            45 - frequency of most frequent value

# Get Column Data Types

In [6]:
#get column data types
print (f"Data Types: \n{dfSales_Features_DataSet.dtypes}")

Data Types:
Unnamed: 0        int64
Store             int64
Date                str
Temperature     float64
Fuel_Price      float64
MarkDown1       float64
MarkDown2       float64
MarkDown3       float64
MarkDown4       float64
MarkDown5       float64
CPI             float64
Unemployment    float64
IsHoliday          bool
dtype: object

## Observations - Sales_Features_DataSet

- Date is a string - needs conversion to datetime. 
- Other column types look ok

## Get Schema Statistics

Look for duplicates and missing values

In [7]:
#get column statistics
modETL.funcGetStatistics(dfSales_Features_DataSet)

DataFrame Statistics:
======================
        Unnamed: 0        Store  Temperature   Fuel_Price      MarkDown1  \
count  8190.000000  8190.000000  8190.000000  8190.000000    4032.000000
mean   4094.500000    23.000000    59.356198     3.405992    7032.371786
std    2364.393685    12.987966    18.678607     0.431337    9262.747448
min       0.000000     1.000000    -7.290000     2.472000   -2781.450000
25%    2047.250000    12.000000    45.902500     3.041000    1577.532500
50%    4094.500000    23.000000    60.710000     3.513000    4743.580000
75%    6141.750000    34.000000    73.880000     3.743000    8923.310000
max    8189.000000    45.000000   101.950000     4.468000  103184.980000

           MarkDown2      MarkDown3     MarkDown4      MarkDown5          CPI  \
count    2921.000000    3613.000000   3464.000000    4050.000000  7605.000000
mean     3384.176594    1760.100180   3292.935886    4132.216422   172.460809
std      8793.583016   11276.462208   6792.329861   13086.690278    39.738346
min      -265.760000    -179.260000      0.220000    -185.170000   126.064000
25%        68.880000       6.600000    304.687500    1440.827500   132.364839
50%       364.570000      36.260000   1176.425000    2727.135000   182.764003
75%      2153.350000     163.150000   3310.007500    4832.555000   213.932412
max    104519.540000  149483.310000  67474.850000  771448.100000   228.976456

       Unemployment
count   7605.000000
mean       7.826821
std        1.877259
min        3.684000
25%        6.634000
50%        7.806000
75%        8.567000
max       14.313000


DataFrame Shape:
====================
Rows: 8190, Columns: 13


Missing Values Per Column:
==============================
MarkDown1            - 4158: Missing Values, 50.77% Percent Missing Values
MarkDown2            - 5269: Missing Values, 64.33% Percent Missing Values
MarkDown3            - 4577: Missing Values, 55.89% Percent Missing Values
MarkDown4            - 4726: Missing Values, 57.70% Percent Missing Values
MarkDown5            - 4140: Missing Values, 50.55% Percent Missing Values
CPI                  - 585: Missing Values, 7.14% Percent Missing Values
Unemployment         - 585: Missing Values, 7.14% Percent Missing Values


Duplicate Value Count Per Column:
==============================
Store                Total Values: 8190  Duplicate Values: 8145, 99.45% Percent Duplicate Values
Date                 Total Values: 8190  Duplicate Values: 8008, 97.78% Percent Duplicate Values
Temperature          Total Values: 8190  Duplicate Values: 4012, 48.99% Percent Duplicate Values
Fuel_Price           Total Values: 8190  Duplicate Values: 7179, 87.66% Percent Duplicate Values
MarkDown1            Total Values: 4032  Duplicate Values: 4166, 50.87% Percent Duplicate Values
MarkDown2            Total Values: 2921  Duplicate Values: 5474, 66.84% Percent Duplicate Values
MarkDown3            Total Values: 3613  Duplicate Values: 5304, 64.76% Percent Duplicate Values
MarkDown4            Total Values: 3464  Duplicate Values: 4784, 58.41% Percent Duplicate Values
MarkDown5            Total Values: 4050  Duplicate Values: 4144, 50.60% Percent Duplicate Values
CPI                  Total Values: 7605  Duplicate Values: 5684, 69.40% Percent Duplicate Values
Unemployment         Total Values: 7605  Duplicate Values: 7785, 95.05% Percent Duplicate Values
IsHoliday            Total Values: 8190  Duplicate Values: 8188, 99.98% Percent Duplicate Values

## Observations - Sales_Features_DataSet

Date is a string - needs conversion to datetime  
Other column types look ok
If unnamed causes issues later on will drop the column!

Observations:
- High levels of missing values in markdown columns which will need addressing
- High duplicates but this is to be expected as store number/date and department would be repeated

---

## Observations - Sales_Features_DataSet

Missing values for columns:
MarkDown1, MarkDown2, MarkDown3, MarkDown4, MarkDown5
CPI, Employment

CPI and Employment are not used in this analysis so will be dropped from the dataset later on

## Get Unique Values - Sales_Features_DataSet

In [8]:
#show unique values count
modETL.funcGetUniqueValuesCount(dfSales_Features_DataSet)

DataFrame Unique Values Per Column:
===================================
Unnamed: 0           - 8190: Unique Values Out Of 8190 Total Values
Store                - 45: Unique Values Out Of 8190 Total Values
Date                 - 182: Unique Values Out Of 8190 Total Values
Temperature          - 4178: Unique Values Out Of 8190 Total Values
Fuel_Price           - 1011: Unique Values Out Of 8190 Total Values
MarkDown1            - 4023: Unique Values Out Of 4032 Total Values
MarkDown2            - 2715: Unique Values Out Of 2921 Total Values
MarkDown3            - 2885: Unique Values Out Of 3613 Total Values
MarkDown4            - 3405: Unique Values Out Of 3464 Total Values
MarkDown5            - 4045: Unique Values Out Of 4050 Total Values
CPI                  - 2505: Unique Values Out Of 7605 Total Values
Unemployment         - 404: Unique Values Out Of 7605 Total Values
IsHoliday            - 2: Unique Values Out Of 8190 Total Values

## Observations - Sales_Features_DataSet

Store has 45 unique values  
Date has 182 unique values  
Temperature has 4178 unique values
Fuel_Price has 1011 unique values
MarkDown1 has 4023 unique values
MarkDown2 has 2715 unique values
MarkDown3 has 2885 unique values
MarkDown4 has 3405 unique values
MarkDown5 has 4045 unique values
CPI has 2505 unique values
Unemployment has 404 unique values
IsHoliday has 2 unique values

## Get Categorical Value Distribution

In [9]:
#get categorical distribution  no needed as only one string value: Date
#and that will converted to datetime later on

# Section 2

- If missing values determine what to fill with (mean, mode or categorical something else)
- Transform data types if necessary

In [10]:
## Create Copy Of DataFrame
dfSales_Features_DataSet_Work = dfSales_Features_DataSet.copy()

## Replace Missing Values With ZERO For MarkDown Columns

In [11]:
#replace missing values for markdown columns with zero. 
#Copilot created code applied naming conventions

lstMarkDownColumns = ["MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5"]
#replace missing values
dfSales_Features_DataSet_Work[lstMarkDownColumns] = dfSales_Features_DataSet_Work[lstMarkDownColumns].fillna(0)

# verify
dfSales_Features_DataSet_Work[lstMarkDownColumns].isna().sum()

MarkDown1    0
MarkDown2    0
MarkDown3    0
MarkDown4    0
MarkDown5    0
dtype: int64

## Observations - Sales_Features_DataSet

Worked! Thanks Copilot, no missing values in the MarkDown numeric columns

Missing values remain the same yet the columns are now without NaN/null values
At this point not concerned, at least the data is clean...

## Strip Spaces From Date Column

In [12]:
#remove spaces from Date column (string datatype)
for objColumn in ["Date"]:
    dfSales_Features_DataSet_Work[objColumn] = dfSales_Features_DataSet_Work[objColumn].str.strip()
    
#show first 50 rows to check    
dfSales_Features_DataSet_Work.head(50)

,Unnamed: 0,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,0,1,05/02/2010,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,False
1,1,1,12/02/2010,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,True
2,2,1,19/02/2010,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,False
3,3,1,26/02/2010,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,False
4,4,1,05/03/2010,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,False
5,5,1,12/03/2010,57.79,2.667,0.0,0.0,0.0,0.0,0.0,211.380643,8.106,False
6,6,1,19/03/2010,54.58,2.720,0.0,0.0,0.0,0.0,0.0,211.215635,8.106,False
7,7,1,26/03/2010,51.45,2.732,0.0,0.0,0.0,0.0,0.0,211.018042,8.106,False
8,8,1,02/04/2010,62.27,2.719,0.0,0.0,0.0,0.0,0.0,210.820450,7.808,False
9,9,1,09/04/2010,65.86,2.770,0.0,0.0,0.0,0.0,0.0,210.622857,7.808,False
10,10,1,16/04/2010,66.32,2.808,0.0,0.0,0.0,0.0,0.0,210.488700,7.808,False
11,11,1,23/04/2010,64.84,2.795,0.0,0.0,0.0,0.0,0.0,210.439123,7.808,False
12,12,1,30/04/2010,67.41,2.780,0.0,0.0,0.0,0.0,0.0,210.389546,7.808,False
13,13,1,07/05/2010,72.55,2.835,0.0,0.0,0.0,0.0,0.0,210.339968,7.808,False
14,14,1,14/05/2010,74.78,2.854,0.0,0.0,0.0,0.0,0.0,210.337426,7.808,False
15,15,1,21/05/2010,76.44,2.826,0.0,0.0,0.0,0.0,0.0,210.617093,7.808,False
16,16,1,28/05/2010,80.44,2.759,0.0,0.0,0.0,0.0,0.0,210.896761,7.808,False
17,17,1,04/06/2010,80.69,2.705,0.0,0.0,0.0,0.0,0.0,211.176428,7.808,False
18,18,1,11/06/2010,80.43,2.668,0.0,0.0,0.0,0.0,0.0,211.456095,7.808,False
19,19,1,18/06/2010,84.11,2.637,0.0,0.0,0.0,0.0,0.0,211.453772,7.808,False
20,20,1,25/06/2010,84.34,2.653,0.0,0.0,0.0,0.0,0.0,211.338653,7.808,False
21,21,1,02/07/2010,80.91,2.669,0.0,0.0,0.0,0.0,0.0,211.223533,7.787,False
22,22,1,09/07/2010,80.48,2.642,0.0,0.0,0.0,0.0,0.0,211.108414,7.787,False
23,23,1,16/07/2010,83.15,2.623,0.0,0.0,0.0,0.0,0.0,211.100385,7.787,False
24,24,1,23/07/2010,83.36,2.608,0.0,0.0,0.0,0.0,0.0,211.235144,7.787,False
25,25,1,30/07/2010,81.84,2.640,0.0,0.0,0.0,0.0,0.0,211.369903,7.787,False
26,26,1,06/08/2010,87.16,2.627,0.0,0.0,0.0,0.0,0.0,211.504662,7.787,False
27,27,1,13/08/2010,87.00,2.692,0.0,0.0,0.0,0.0,0.0,211.639421,7.787,False
28,28,1,20/08/2010,86.65,2.664,0.0,0.0,0.0,0.0,0.0,211.603363,7.787,False
29,29,1,27/08/2010,85.22,2.619,0.0,0.0,0.0,0.0,0.0,211.567306,7.787,False
30,30,1,03/09/2010,81.21,2.577,0.0,0.0,0.0,0.0,0.0,211.531248,7.787,False
31,31,1,10/09/2010,78.69,2.565,0.0,0.0,0.0,0.0,0.0,211.495190,7.787,True
32,32,1,17/09/2010,82.11,2.582,0.0,0.0,0.0,0.0,0.0,211.522460,7.787,False
33,33,1,24/09/2010,80.94,2.624,0.0,0.0,0.0,0.0,0.0,211.597225,7.787,False
34,34,1,01/10/2010,71.89,2.603,0.0,0.0,0.0,0.0,0.0,211.671989,7.838,False
35,35,1,08/10/2010,63.93,2.633,0.0,0.0,0.0,0.0,0.0,211.746754,7.838,False
36,36,1,15/10/2010,67.18,2.720,0.0,0.0,0.0,0.0,0.0,211.813744,7.838,False
37,37,1,22/10/2010,69.86,2.725,0.0,0.0,0.0,0.0,0.0,211.861294,7.838,False
38,38,1,29/10/2010,69.64,2.716,0.0,0.0,0.0,0.0,0.0,211.908844,7.838,False
39,39,1,05/11/2010,58.74,2.689,0.0,0.0,0.0,0.0,0.0,211.956394,7.838,False
40,40,1,12/11/2010,59.61,2.728,0.0,0.0,0.0,0.0,0.0,212.003944,7.838,False
41,41,1,19/11/2010,51.41,2.771,0.0,0.0,0.0,0.0,0.0,211.889674,7.838,False
42,42,1,26/11/2010,64.52,2.735,0.0,0.0,0.0,0.0,0.0,211.748433,7.838,True
43,43,1,03/12/2010,49.27,2.708,0.0,0.0,0.0,0.0,0.0,211.607193,7.838,False
44,44,1,10/12/2010,46.33,2.843,0.0,0.0,0.0,0.0,0.0,211.465953,7.838,False
45,45,1,17/12/2010,49.84,2.869,0.0,0.0,0.0,0.0,0.0,211.405312,7.838,False
46,46,1,24/12/2010,52.33,2.886,0.0,0.0,0.0,0.0,0.0,211.405122,7.838,False
47,47,1,31/12/2010,48.43,2.943,0.0,0.0,0.0,0.0,0.0,211.404932,7.838,True
48,48,1,07/01/2011,48.27,2.976,0.0,0.0,0.0,0.0,0.0,211.404742,7.742,False
49,49,1,14/01/2011,35.40,2.983,0.0,0.0,0.0,0.0,0.0,211.457411,7.742,False

## Observations - Sales_Features_DataSet

No data corruptions

## Validate Numerical Values For Columns Used In Analysis

- see if Stores column has values less than 1
- see if MarkDown1 column has values less than 1
- see if MarkDown2 column has values less than 1
- see if MarkDown3 column has values less than 1
- see if MarkDown4 column has values less than 1
- see if MarkDown5 column has values less than 1

In [13]:
#get count of how many values in Stores column are less than 1
intLessThanOne = (dfSales_Features_DataSet_Work["Store"] < 1).sum()
#print result
intLessThanOne

np.int64(0)

---

## Observations - Sales_Features_DataSet

Values for Store in acceptable limits

## Check All MarkDown Columns For Values Less Than 0

In [14]:
#check MarkDown columns for < 0

for intNum in range(1,6):
    intLessThanOne = (dfSales_Features_DataSet_Work[ f"MarkDown{intNum}" ] < 0).sum()
    #print result
    print( f"MarkDown Column {intNum} Has Values Less Than Zero? {intLessThanOne > 0}")
    
    
#Check findings    
dfSales_Features_DataSet_Work.query( "MarkDown1 <0 or MarkDown2 <0 or MarkDown3 <0 or MarkDown4 <0 or MarkDown5 <0")

MarkDown Column 1 Has Values Less Than Zero? True
MarkDown Column 2 Has Values Less Than Zero? True
MarkDown Column 3 Has Values Less Than Zero? True
MarkDown Column 4 Has Values Less Than Zero? False
MarkDown Column 5 Has Values Less Than Zero? True

,Unnamed: 0,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
657,657,4,23/03/2012,59.07,3.759,8806.80,-10.50,5.99,739.14,4396.97,130.896645,4.607,False
860,860,5,17/08/2012,87.52,3.571,1649.56,-10.98,2.31,1955.75,1205.23,222.627675,5.603,False
873,873,5,16/11/2012,56.89,3.252,1631.01,-35.74,15.46,326.59,2310.83,224.106624,5.422,False
893,893,5,05/04/2013,61.88,3.583,9023.29,927.32,170.24,405.30,-185.17,225.682320,5.278,False
1063,1063,6,11/01/2013,48.26,3.243,5510.29,33063.57,-0.86,693.10,3418.77,225.832011,5.372,False
1265,1265,7,31/05/2013,50.70,3.870,2350.78,-7.76,91.59,166.86,540.89,NaN,NaN,False
1587,1587,9,10/08/2012,88.66,3.494,3180.78,-9.94,1.40,2112.03,2314.58,225.717009,5.277,False
1591,1591,9,07/09/2012,87.93,3.730,4837.99,-5.96,22.74,602.80,1377.59,226.210354,5.277,True
1611,1611,9,25/01/2013,49.14,3.227,200.46,348.20,-14.29,59.00,2162.77,228.030618,5.049,False
1615,1615,9,22/02/2013,45.91,3.597,2810.86,1405.04,-179.26,63.12,3593.56,228.205445,5.049,False
1748,1748,10,16/03/2012,62.11,4.273,3977.45,-10.50,6.03,1928.50,2273.92,130.826193,7.545,False
1766,1766,10,20/07/2012,84.45,3.589,6596.80,-1.60,44.60,4275.27,10650.28,130.701290,7.170,False
1987,1987,11,19/04/2013,70.87,3.451,3808.66,-15.45,142.70,529.99,2742.75,228.729864,5.999,False
2128,2128,12,06/07/2012,89.13,3.765,10804.73,-0.60,3.33,5397.84,4395.03,130.719633,10.926,False
2330,2330,13,23/11/2012,46.21,3.562,2088.09,-0.05,149483.31,756.99,1176.10,131.376667,5.621,True
2337,2337,13,11/01/2013,20.00,2.982,3726.82,17212.29,-23.97,116.72,2662.80,131.957000,5.372,False
2493,2493,14,13/07/2012,79.97,3.523,9158.47,-2.50,5.37,4516.68,2574.55,191.168519,8.684,False
2681,2681,15,24/08/2012,66.98,3.997,3669.07,-6.69,0.00,2813.59,1610.18,138.281452,8.193,False
2690,2690,15,26/10/2012,55.75,4.071,4657.77,-7.01,100.00,1077.51,1234.65,138.728161,7.992,False
2865,2865,16,07/09/2012,60.09,3.596,2291.22,-9.98,37.43,411.53,1576.74,198.095048,6.061,True
3241,3241,18,30/11/2012,34.72,3.713,2490.24,-0.01,4412.81,79.08,4115.57,138.402033,8.243,False
3392,3392,19,27/04/2012,42.45,4.163,3735.30,-265.76,52.82,67.72,2959.27,137.978133,8.150,False
3593,3593,20,07/09/2012,76.36,3.911,11783.56,-0.99,83.85,1938.40,3708.67,215.218957,7.280,True
3978,3978,22,01/02/2013,32.63,3.608,19102.16,1403.25,-89.10,43742.76,1549.09,142.868066,7.328,False
3981,3981,22,22/02/2013,30.28,3.866,10313.25,4247.11,-2.58,2512.93,3651.16,142.970823,7.328,False
4162,4162,23,15/02/2013,25.39,3.807,-563.90,2825.54,21.00,5510.21,4677.39,138.900429,3.932,False
4304,4304,24,11/05/2012,58.70,4.055,6503.15,-192.00,97.28,1798.06,1286.62,138.088267,8.983,False
4529,4529,25,08/03/2013,28.79,3.860,20996.56,-3.27,17.57,3982.88,1833.43,217.293249,7.439,False
5036,5036,28,08/06/2012,84.83,4.103,9026.85,101.20,-29.10,833.67,11752.37,130.889677,11.627,False
5437,5437,30,22/02/2013,49.09,3.597,-2781.45,297.30,0.00,0.00,791.67,224.054703,6.237,False
5572,5572,31,30/03/2012,67.87,3.845,9546.49,584.62,-1.00,1334.23,3691.10,220.999125,7.057,False
5576,5576,31,27/04/2012,69.21,3.814,2973.44,-0.91,10.16,542.50,9196.82,221.255812,6.891,False
5785,5785,32,02/11/2012,46.32,3.604,11156.55,5943.82,24.22,441.71,-37.02,199.290867,7.557,False
6141,6141,34,07/09/2012,78.26,3.709,8791.04,-5.98,25.77,3473.34,1789.37,130.932548,9.285,True
6313,6313,35,29/06/2012,73.94,3.506,11690.61,-7.60,0.00,3457.25,5129.74,142.192038,8.876,False
6354,6354,35,12/04/2013,53.28,3.724,4828.15,4850.29,-44.54,878.64,1098.99,143.220074,8.360,False
6466,6466,36,09/12/2011,50.64,3.147,0.00,0.00,-0.87,0.00,1129.02,217.664588,7.716,False
6514,6514,36,09/11/2012,68.58,3.313,-16.93,850.05,0.00,0.00,733.24,222.150626,6.228,False
6518,6518,36,07/12/2012,68.04,3.204,-772.21,0.00,0.00,0.00,692.10,222.325549,6.228,False
6885,6885,38,28/12/2012,43.35,3.480,1328.51,1297.28,-0.73,41.34,774.32,131.747000,10.199,True
7032,7032,39,27/04/2012,69.11,3.814,5821.79,0.00,-0.20,164.58,8663.37,220.301448,6.989,False
7069,7069,39,11/01/2013,53.33,3.243,4903.75,13676.23,-17.44,245.14,22400.65,222.864420,6.266,False
7401,7401,41,01/06/2012,57.29,3.764,9160.25,-2.00,127.56,1850.68,2652.68,197.621895,6.547,False
7413,7413,41,24/08/2012,69.07,3.558,6068.27,-20.00,85.74,3710.05,2287.85,198.098420,6.432,False

## Observations - Sales_Features_DataSet

MarkDown columns 1, 2, 3 and 5 have values less than 0
Being as markdowns can be negative by nature am happy to ignore

## Data Transformations/Feature Engineering

Convert Date column to datetime format

In [15]:
#convert Date column to datetime format
dfSales_Features_DataSet_Work["Date"] = pd.to_datetime(dfSales_Features_DataSet["Date"], format="%d/%m/%Y")

#check results
dfSales_Features_DataSet_Work.head(50)

,Unnamed: 0,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,0,1,2010-02-05,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,False
1,1,1,2010-02-12,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,True
2,2,1,2010-02-19,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,False
3,3,1,2010-02-26,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,False
4,4,1,2010-03-05,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,False
5,5,1,2010-03-12,57.79,2.667,0.0,0.0,0.0,0.0,0.0,211.380643,8.106,False
6,6,1,2010-03-19,54.58,2.720,0.0,0.0,0.0,0.0,0.0,211.215635,8.106,False
7,7,1,2010-03-26,51.45,2.732,0.0,0.0,0.0,0.0,0.0,211.018042,8.106,False
8,8,1,2010-04-02,62.27,2.719,0.0,0.0,0.0,0.0,0.0,210.820450,7.808,False
9,9,1,2010-04-09,65.86,2.770,0.0,0.0,0.0,0.0,0.0,210.622857,7.808,False
10,10,1,2010-04-16,66.32,2.808,0.0,0.0,0.0,0.0,0.0,210.488700,7.808,False
11,11,1,2010-04-23,64.84,2.795,0.0,0.0,0.0,0.0,0.0,210.439123,7.808,False
12,12,1,2010-04-30,67.41,2.780,0.0,0.0,0.0,0.0,0.0,210.389546,7.808,False
13,13,1,2010-05-07,72.55,2.835,0.0,0.0,0.0,0.0,0.0,210.339968,7.808,False
14,14,1,2010-05-14,74.78,2.854,0.0,0.0,0.0,0.0,0.0,210.337426,7.808,False
15,15,1,2010-05-21,76.44,2.826,0.0,0.0,0.0,0.0,0.0,210.617093,7.808,False
16,16,1,2010-05-28,80.44,2.759,0.0,0.0,0.0,0.0,0.0,210.896761,7.808,False
17,17,1,2010-06-04,80.69,2.705,0.0,0.0,0.0,0.0,0.0,211.176428,7.808,False
18,18,1,2010-06-11,80.43,2.668,0.0,0.0,0.0,0.0,0.0,211.456095,7.808,False
19,19,1,2010-06-18,84.11,2.637,0.0,0.0,0.0,0.0,0.0,211.453772,7.808,False
20,20,1,2010-06-25,84.34,2.653,0.0,0.0,0.0,0.0,0.0,211.338653,7.808,False
21,21,1,2010-07-02,80.91,2.669,0.0,0.0,0.0,0.0,0.0,211.223533,7.787,False
22,22,1,2010-07-09,80.48,2.642,0.0,0.0,0.0,0.0,0.0,211.108414,7.787,False
23,23,1,2010-07-16,83.15,2.623,0.0,0.0,0.0,0.0,0.0,211.100385,7.787,False
24,24,1,2010-07-23,83.36,2.608,0.0,0.0,0.0,0.0,0.0,211.235144,7.787,False
25,25,1,2010-07-30,81.84,2.640,0.0,0.0,0.0,0.0,0.0,211.369903,7.787,False
26,26,1,2010-08-06,87.16,2.627,0.0,0.0,0.0,0.0,0.0,211.504662,7.787,False
27,27,1,2010-08-13,87.00,2.692,0.0,0.0,0.0,0.0,0.0,211.639421,7.787,False
28,28,1,2010-08-20,86.65,2.664,0.0,0.0,0.0,0.0,0.0,211.603363,7.787,False
29,29,1,2010-08-27,85.22,2.619,0.0,0.0,0.0,0.0,0.0,211.567306,7.787,False
30,30,1,2010-09-03,81.21,2.577,0.0,0.0,0.0,0.0,0.0,211.531248,7.787,False
31,31,1,2010-09-10,78.69,2.565,0.0,0.0,0.0,0.0,0.0,211.495190,7.787,True
32,32,1,2010-09-17,82.11,2.582,0.0,0.0,0.0,0.0,0.0,211.522460,7.787,False
33,33,1,2010-09-24,80.94,2.624,0.0,0.0,0.0,0.0,0.0,211.597225,7.787,False
34,34,1,2010-10-01,71.89,2.603,0.0,0.0,0.0,0.0,0.0,211.671989,7.838,False
35,35,1,2010-10-08,63.93,2.633,0.0,0.0,0.0,0.0,0.0,211.746754,7.838,False
36,36,1,2010-10-15,67.18,2.720,0.0,0.0,0.0,0.0,0.0,211.813744,7.838,False
37,37,1,2010-10-22,69.86,2.725,0.0,0.0,0.0,0.0,0.0,211.861294,7.838,False
38,38,1,2010-10-29,69.64,2.716,0.0,0.0,0.0,0.0,0.0,211.908844,7.838,False
39,39,1,2010-11-05,58.74,2.689,0.0,0.0,0.0,0.0,0.0,211.956394,7.838,False
40,40,1,2010-11-12,59.61,2.728,0.0,0.0,0.0,0.0,0.0,212.003944,7.838,False
41,41,1,2010-11-19,51.41,2.771,0.0,0.0,0.0,0.0,0.0,211.889674,7.838,False
42,42,1,2010-11-26,64.52,2.735,0.0,0.0,0.0,0.0,0.0,211.748433,7.838,True
43,43,1,2010-12-03,49.27,2.708,0.0,0.0,0.0,0.0,0.0,211.607193,7.838,False
44,44,1,2010-12-10,46.33,2.843,0.0,0.0,0.0,0.0,0.0,211.465953,7.838,False
45,45,1,2010-12-17,49.84,2.869,0.0,0.0,0.0,0.0,0.0,211.405312,7.838,False
46,46,1,2010-12-24,52.33,2.886,0.0,0.0,0.0,0.0,0.0,211.405122,7.838,False
47,47,1,2010-12-31,48.43,2.943,0.0,0.0,0.0,0.0,0.0,211.404932,7.838,True
48,48,1,2011-01-07,48.27,2.976,0.0,0.0,0.0,0.0,0.0,211.404742,7.742,False
49,49,1,2011-01-14,35.40,2.983,0.0,0.0,0.0,0.0,0.0,211.457411,7.742,False

## Remove Unnecessary Columns

In [16]:
#going to remove:
#fuel_price, CPI
dfSales_Features_DataSet_Work.drop(columns=["Fuel_Price", "CPI"], inplace=True)

#check results
dfSales_Features_DataSet_Work.info()

<class 'pandas.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    8190 non-null   int64
 1   Store         8190 non-null   int64
 2   Date          8190 non-null   datetime64[us]
 3   Temperature   8190 non-null   float64
 4   MarkDown1     8190 non-null   float64
 5   MarkDown2     8190 non-null   float64
 6   MarkDown3     8190 non-null   float64
 7   MarkDown4     8190 non-null   float64
 8   MarkDown5     8190 non-null   float64
 9   Unemployment  7605 non-null   float64
 10  IsHoliday     8190 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(7), int64(2)
memory usage: 648.0 KB

## Observations - Sales_Features_DataSet

Columns confirmed removed:

Fuel_Price, CPI, Unemployment

## Save Work DataFrame To CSV File

In [17]:
#create list of columns new and old JUST what is actually needed
lstColumns = [
                #original columns
                "Store","Date","Temperature",
                "MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5",
                "IsHoliday", "Unemployment"
              ]

#create new DataFrame for cleaned data
dfCleaned = dfSales_Features_DataSet_Work[lstColumns].copy()

modETL.funcSaveDataFrameToCleanedFile(dfCleaned)

#Note: excluded column: Dept as not in the hypothesis analysis which is a nice way
#      avoiding the fact I don't know just how to plot a chart with 98 departments
#      and have it readable!

Saved: Features_DataSet To Visualisation Folder

# Conclusions and Next Steps

ETL went well, DataSet ready for use